import type { Fighters } from '@/types/fighters'

export const FIGHTERS: Fighters[] = [
  {
    id: 'edu-aguirre',
    name: 'Edu Aguirre',
    realName: 'Eduardo Aguirre',
    gender: 'masculino',
    birthDate: new Date(1988, 0, 14),
    height: 1.83,
    age: 38,
    weight: 80,
    country: 'es',
    city: 'Madrid',
    versus: 'gaston-edul',
    socials: [],
    clips: [],
    bio: 'Periodista deportivo español, conocido por su trabajo en El Chiringuito de Jugones. Debuta en El Ring para demostrar su disciplina y pasión por el deporte en este duelo de periodistas.',
    stats: { power: 65, speed: 70, stamina: 75, technique: 60, defense: 65 }
  },
  {
    id: 'gaston-edul',
    name: 'Gastón Edul',
    realName: 'Gastón Edul',
    gender: 'masculino',
    birthDate: new Date(1995, 11, 31),
    height: 1.78,
    age: 30,
    weight: 75,
    country: 'ar',
    city: 'Buenos Aires',
    versus: 'edu-aguirre',
    socials: [],
    clips: [],
    bio: 'Periodista deportivo argentino, destacado por su cobertura de la Selección Argentina. Cruza el charco para enfrentarse a su colega español en un combate que trasciende fronteras.',
    stats: { power: 60, speed: 75, stamina: 70, technique: 65, defense: 60 }
  },
  {
    id: 'fabiana-sevillano',
    name: 'Fabiana Sevillano',
    realName: 'Fabiana Sevillano',
    gender: 'femenino',
    birthDate: new Date(2000, 0, 1),
    height: 1.65,
    age: 26,
    weight: 55,
    country: 'es',
    city: 'Sevilla',
    versus: 'la-parce',
    socials: [],
    clips: [],
    bio: 'TikToker e influencer española. Con su carisma y energía, Fabiana busca conquistar el ring de su tierra natal en Sevilla.',
    stats: { power: 55, speed: 80, stamina: 65, technique: 70, defense: 60 }
  },
  {
    id: 'la-parce',
    name: 'La Parce',
    realName: 'La Parce',
    gender: 'femenino',
    birthDate: new Date(1998, 0, 1),
    height: 1.60,
    age: 28,
    weight: 52,
    country: 'co',
    city: 'Medellín',
    versus: 'fabiana-sevillano',
    socials: [],
    clips: [],
    bio: 'Streamer colombiana y presidenta en la Queens League. Una líder nata que viene a demostrar que su determinación no tiene límites.',
    stats: { power: 50, speed: 85, stamina: 60, technique: 75, defense: 55 }
  },
  {
    id: 'clersss',
    name: 'Clersss',
    realName: 'Clersss',
    gender: 'femenino',
    birthDate: new Date(2001, 0, 1),
    height: 1.62,
    age: 25,
    weight: 54,
    country: 'es',
    city: 'Madrid',
    versus: 'natalia-mx',
    socials: [],
    clips: [],
    bio: 'Creadora de contenido española. Disciplinada y constante, Clersss se prepara para dar la sorpresa en esta edición de La Velada.',
    stats: { power: 60, speed: 70, stamina: 80, technique: 65, defense: 70 }
  },
  {
    id: 'natalia-mx',
    name: 'Natalia MX',
    realName: 'Natalia MX',
    gender: 'femenino',
    birthDate: new Date(2000, 0, 1),
    height: 1.68,
    age: 26,
    weight: 58,
    country: 'mx',
    city: 'Ciudad de México',
    versus: 'clersss',
    socials: [],
    clips: [],
    bio: 'Creadora de contenido mexicana. Con la fuerza de México tras ella, Natalia llega dispuesta a dejarlo todo en el cuadrilátero.',
    stats: { power: 70, speed: 65, stamina: 75, technique: 60, defense: 75 }
  },
  {
    id: 'kidd-keo',
    name: 'Kidd Keo',
    realName: 'Padua Keoma Salas Sánchez',
    gender: 'masculino',
    birthDate: new Date(1995, 8, 27),
    height: 1.76,
    age: 30,
    weight: 70,
    country: 'es',
    city: 'Alicante',
    versus: 'lit-killah',
    socials: [],
    clips: [],
    bio: 'Artista y rapero español referente del trap. Cambia los escenarios por el ring en un duelo de altura contra la escena argentina.',
    stats: { power: 75, speed: 70, stamina: 65, technique: 70, defense: 65 }
  },
  {
    id: 'lit-killah',
    name: 'Lit Killah',
    realName: 'Mauro Román Monzón',
    gender: 'masculino',
    birthDate: new Date(1999, 9, 4),
    height: 1.75,
    age: 26,
    weight: 68,
    country: 'ar',
    city: 'Buenos Aires',
    versus: 'kidd-keo',
    socials: [],
    clips: [],
    bio: 'Artista, trapper y freestyler argentino. El "dueño de la mansión" viene a demostrar que su agilidad mental también se traduce en agilidad física.',
    stats: { power: 70, speed: 75, stamina: 70, technique: 65, defense: 70 }
  },
  {
    id: 'alondrissa',
    name: 'Alondrissa',
    realName: 'Alondrissa',
    gender: 'femenino',
    birthDate: new Date(2002, 0, 1),
    height: 1.58,
    age: 24,
    weight: 50,
    country: 'pr',
    city: 'San Juan',
    versus: 'angie-velasco',
    socials: [],
    clips: [],
    bio: 'Creadora de contenido puertorriqueña. Con el ritmo y la garra de la isla, Alondrissa se enfrenta a uno de sus mayores retos.',
    stats: { power: 55, speed: 85, stamina: 70, technique: 65, defense: 60 }
  },
  {
    id: 'angie-velasco',
    name: 'Angie Velasco',
    realName: 'Angie Velasco',
    gender: 'femenino',
    birthDate: new Date(1998, 11, 25),
    height: 1.64,
    age: 27,
    weight: 56,
    country: 'ar',
    city: 'Rosario',
    versus: 'alondrissa',
    socials: [],
    clips: [],
    bio: 'YouTuber argentina con una legión de seguidores. Su creatividad y perseverancia serán sus mejores armas en el combate.',
    stats: { power: 50, speed: 80, stamina: 75, technique: 70, defense: 65 }
  },
  {
    id: 'gero-arias',
    name: 'Gero Arias',
    realName: 'Geronimo Arias',
    gender: 'masculino',
    birthDate: new Date(2003, 0, 1),
    height: 1.85,
    age: 23,
    weight: 85,
    country: 'ar',
    city: 'Buenos Aires',
    versus: 'viruzz',
    socials: [],
    clips: [],
    bio: 'Influencer de fitness argentino conocido por sus retos de dominadas. Su fuerza física es incuestionable, pero ¿podrá con la experiencia de un veterano?',
    stats: { power: 90, speed: 70, stamina: 85, technique: 55, defense: 60 }
  },
  {
    id: 'viruzz',
    name: 'Viruzz',
    realName: 'Víctor Mélida Cambra',
    gender: 'masculino',
    birthDate: new Date(1992, 4, 1),
    height: 1.82,
    age: 34,
    weight: 87,
    country: 'es',
    city: 'Zaragoza',
    versus: 'gero-arias',
    socials: [],
    clips: [],
    bio: 'El papá de La Velada regresa. Con múltiples victorias a sus espaldas, Viruzz busca consolidar su leyenda frente a la nueva generación de atletas.',
    stats: { power: 85, speed: 75, stamina: 80, technique: 90, defense: 85 }
  },
  {
    id: 'roro',
    name: 'Roro',
    realName: 'Rocío López Bueno',
    gender: 'femenino',
    birthDate: new Date(2002, 2, 1),
    height: 1.49,
    age: 24,
    weight: 47,
    country: 'es',
    city: 'Barcelona',
    versus: 'samy-rivers',
    socials: [],
    clips: [],
    bio: 'La tiktoker revelación que cocina desde cero. Ahora, Roro prepara una receta para la victoria frente a una de las rivales más duras de la historia del evento.',
    stats: { power: 55, speed: 75, stamina: 70, technique: 65, defense: 80 }
  },
  {
    id: 'samy-rivers',
    name: 'Samy Rivers',
    realName: 'Samantha Rivera',
    gender: 'femenino',
    birthDate: new Date(1998, 4, 4),
    height: 1.58,
    age: 28,
    weight: 52,
    country: 'mx',
    city: 'Monterrey',
    versus: 'roro',
    socials: [],
    clips: [],
    bio: 'La Patrona regresa al ring. Después de su doble combate histórico, la presidenta de PIO FC busca una nueva victoria en territorio español.',
    stats: { power: 75, speed: 70, stamina: 90, technique: 85, defense: 80 }
  },
  {
    id: 'marta-diaz',
    name: 'Marta Díaz',
    realName: 'Marta Díaz García',
    gender: 'femenino',
    birthDate: new Date(2000, 9, 30),
    height: 1.69,
    age: 25,
    weight: 58,
    country: 'es',
    city: 'Madrid',
    versus: 'tatiana-kaer',
    socials: [],
    clips: [],
    bio: 'Una de las influencers más importantes de España. Marta Díaz se sube al ring para demostrar su capacidad de superación y esfuerzo.',
    stats: { power: 60, speed: 75, stamina: 70, technique: 65, defense: 70 }
  },
  {
    id: 'tatiana-kaer',
    name: 'Tatiana Kaer',
    realName: 'Tatiana Kaer',
    gender: 'femenino',
    birthDate: new Date(1999, 0, 1),
    height: 1.74,
    age: 27,
    weight: 59,
    country: 'es',
    city: 'Madrid',
    versus: 'marta-diaz',
    socials: [],
    clips: [],
    bio: 'Modelo e influencer española. Con una presencia imponente, Tatiana busca demostrar que su determinación es tan fuerte como su estilo.',
    stats: { power: 65, speed: 70, stamina: 75, technique: 70, defense: 75 }
  },
  {
    id: 'yosoyplex',
    name: 'YoSoyPlex',
    realName: 'Daniel Alonso',
    gender: 'masculino',
    birthDate: new Date(2001, 8, 20),
    height: 1.95,
    age: 24,
    weight: 95,
    country: 'es',
    city: 'Madrid',
    versus: 'fernanfloo',
    socials: [],
    clips: [],
    bio: 'El gigante de YouTube España. Después de dar la vuelta al mundo, Plex se enfrenta a su mayor reto físico en el Co-Main Event.',
    stats: { power: 85, speed: 80, stamina: 75, technique: 70, defense: 65 }
  },
  {
    id: 'fernanfloo',
    name: 'Fernanfloo',
    realName: 'Luis Fernando Flores Alvarado',
    gender: 'masculino',
    birthDate: new Date(1993, 6, 7),
    height: 1.86,
    age: 33,
    weight: 78,
    country: 'sv',
    city: 'San Salvador',
    versus: 'yosoyplex',
    socials: [],
    clips: [],
    bio: 'La leyenda de YouTube. Fernanfloo regresa para un combate épico frente a la nueva ola de creadores. La curiosidad mató al gato, pero ¿podrá Fernan con Plex?',
    stats: { power: 75, speed: 85, stamina: 70, technique: 80, defense: 70 }
  },
  {
    id: 'illojuan',
    name: 'IlloJuan',
    realName: 'Juan Alberto García',
    gender: 'masculino',
    birthDate: new Date(1994, 5, 22),
    height: 1.85,
    age: 32,
    weight: 82,
    country: 'es',
    city: 'Málaga',
    versus: 'grefg',
    socials: [],
    clips: [],
    bio: 'El Rey de Twitch España. IlloJuan debuta en el Main Event en un combate que paralizará a toda la comunidad. Humildad y guantes frente a frente.',
    stats: { power: 80, speed: 75, stamina: 85, technique: 70, defense: 75 }
  },
  {
    id: 'grefg',
    name: 'TheGrefg',
    realName: 'David Cánovas Martínez',
    gender: 'masculino',
    birthDate: new Date(1997, 3, 24),
    height: 1.79,
    age: 29,
    weight: 74,
    country: 'es',
    city: 'Alhama de Murcia',
    versus: 'illojuan',
    socials: [],
    clips: [],
    bio: 'Un coloso de la creación de contenido. El presidente de Saiyans FC busca cerrar La Velada VI con una victoria histórica en el Main Event.',
    stats: { power: 75, speed: 90, stamina: 80, technique: 85, defense: 80 }
  },
]
